Pageobjects/add company
howtostartautomatedtesting/project-users-bug-red pull request #9
Opened 2022-04-17 15:49 UTC by RamanBohdan

2022-04-17 19:04 UTC, howtostartautomatedtesting requested changes

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +public class CompaniesPageAndAddCompanyPage extends AbstractPage {
Должно быть два класса !!
CompaniesPage.java
AddCompanyPage.java

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "//*[@id='main-menu']/ul/li[3]/a")
попробовать подобрать более "говорящий" xpath

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/p[1]/a")
не находит по данному локатору элемент кнопку Добавить компанию :(

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[1]/td[2]/input")
попробовать подобрать более "говорящий" xpath

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "//*[@id='select2-type-4o-container']")
не находит элемент

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[3]/td[2]/input")
попробовать подобрать более "говорящий" xpath

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[4]/td[2]/input")
попробовать подобрать более "говорящий" xpath

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[5]/td[2]/input")
попробовать подобрать более "говорящий" xpath

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[6]/td[2]/input")
попробовать подобрать более "говорящий" xpath

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[7]/td[2]/input")
попробовать подобрать более "говорящий" xpath

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[8]/td[2]/span/span[1]/span/ul")
попробовать подобрать более "говорящий" xpath

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = " /html/body/div[3]/div[1]/form/table/tbody/tr[9]/td[2]/input")
закрался лишний пробел в начале
и.... попробовать подобрать более "говорящий" xpath

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    private WebElement pressButtonAddCompany;
слово press лишнее в названии.

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +
так же нужно сделать локаторы ко всем подписям label полей ввода информации!

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    public CompaniesPageAndAddCompanyPage openPageCompanies() {
по сути, да этот метод открывает новую страницу,
но по факту этот метод кликает на кнопке Компании.
переименовать!

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    public CompaniesPageAndAddCompanyPage addPageCompanies() {
есть сомнение что в отдельности этот метод будет использоваться, возможно, нет смысла его в принципе создавать!?

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    public CompaniesPageAndAddCompanyPage chooseTypeCompany() {
здесь скорее всего в сигнатуре метода нужно указать параметры которые мы хотим передать, для выбора того или иного типа

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +}
можно еще создать метод, который заполняет все поля формы, и метод который заполняет все поля формы и кликает добавить компанию.

2022-04-17 19:04 UTC, howtostartautomatedtesting commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +}
для пейдж обжекта Компании нужно еще описать
кнопки:
- Пользователи
- Задачи,
- Компании
Заголовок
- Компании
Таблицу
- Тип
- Назване
- Автор
- Дата изменения

2022-04-19 16:52 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +public class CompaniesPageAndAddCompanyPage extends AbstractPage {
исправлено.

2022-04-19 16:53 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "//*[@id='main-menu']/ul/li[3]/a")
исправлено.

2022-04-19 16:53 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/p[1]/a")
исправлено.

2022-04-19 16:53 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[1]/td[2]/input")
исправлено.

2022-04-19 16:53 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "//*[@id='select2-type-4o-container']")
исправлено.

2022-04-19 16:53 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[3]/td[2]/input")
исправлено.

2022-04-19 16:53 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[4]/td[2]/input")
исправлено.

2022-04-19 16:53 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[5]/td[2]/input")
исправлено.

2022-04-19 16:54 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[6]/td[2]/input")
исправлено.

2022-04-19 16:54 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[7]/td[2]/input")
исправлено.

2022-04-19 16:54 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = "/html/body/div[3]/div[1]/form/table/tbody/tr[8]/td[2]/span/span[1]/span/ul")
исправлено.

2022-04-19 16:54 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    @FindBy(xpath = " /html/body/div[3]/div[1]/form/table/tbody/tr[9]/td[2]/input")
исправлено.

2022-04-19 16:55 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    private WebElement pressButtonAddCompany;
исправлено.

2022-04-19 16:55 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    public CompaniesPageAndAddCompanyPage openPageCompanies() {
исправлено.

2022-04-19 16:55 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    public CompaniesPageAndAddCompanyPage addPageCompanies() {
исправлено.

2022-04-19 16:55 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +    public CompaniesPageAndAddCompanyPage chooseTypeCompany() {
исправлено.

2022-04-19 16:55 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +}
исправлено.

2022-04-19 17:18 UTC, RamanBohdan commented on src/test/java/pageobjects/CompaniesPageAndAddCompanyPage.java
> +
исправлено

2022-04-19 17:19 UTC, merged